CC      = arm-none-eabi-gcc
OBJCOPY = arm-none-eabi-objcopy
BUILD_DIR ?= build
OUT_ELF   = $(BUILD_DIR)/stm32f407vet6_uart_dma.elf
OUT_BIN   = $(BUILD_DIR)/stm32f407vet6_uart_dma.bin
MAIN_SRC       = ../stm32f407_uart_dma/main.c
VENDOR_DIR     = ../stm32f407_discovery/vendor
CUBE_ROOT      = ../../../third_party/cache/STM32CubeF4
CMSIS_CORE_INC = $(CUBE_ROOT)/Drivers/CMSIS/Include
CMSIS_DEV_INC  = $(VENDOR_DIR)/include/st
CFLAGS  = -mcpu=cortex-m4 -mthumb -mfpu=fpv4-sp-d16 -mfloat-abi=hard \
          -O2 -g -ffreestanding -fdata-sections -ffunction-sections \
          -DSTM32F407xx -I$(CMSIS_CORE_INC) -I$(CMSIS_DEV_INC) -I..
LDFLAGS = -T ../stm32f407vet6_blink/stm32f407vet6.ld \
          -Wl,--gc-sections -nostartfiles -nostdlib \
          -Wl,--defsym=__libc_init_array=0
OBJS = $(BUILD_DIR)/main.o \
       $(BUILD_DIR)/vendor/st/system_stm32f4xx.o \
       $(BUILD_DIR)/vendor/st/startup_stm32f407xx.o
all: $(OUT_ELF) $(OUT_BIN)
$(BUILD_DIR)/vendor/st: ; mkdir -p $@
$(BUILD_DIR)/main.o: $(MAIN_SRC) | $(BUILD_DIR)
	$(CC) $(CFLAGS) -c $< -o $@
$(BUILD_DIR)/vendor/st/system_stm32f4xx.o: $(VENDOR_DIR)/st/system_stm32f4xx.c | $(BUILD_DIR)/vendor/st
	$(CC) $(CFLAGS) -c $< -o $@
$(BUILD_DIR)/vendor/st/startup_stm32f407xx.o: $(VENDOR_DIR)/st/startup_stm32f407xx.s | $(BUILD_DIR)/vendor/st
	$(CC) $(CFLAGS) -c $< -o $@
$(BUILD_DIR): ; mkdir -p $@
$(OUT_ELF): $(OBJS)
	$(CC) $(CFLAGS) $(OBJS) -o $@ $(LDFLAGS) -lgcc
$(OUT_BIN): $(OUT_ELF)
	$(OBJCOPY) -O binary $< $@
clean: ; rm -rf $(BUILD_DIR)
