{
  "mode": "sequence",
  "stop_on_fail": true,
  "version": 1,
  "groups": [
    {
      "name": "parallel_batch",
      "execution_policy": {
        "kind": "parallel"
      },
      "steps": [
        {
          "pack": "packs/stm32f401rct6_golden.json"
        },
        {
          "pack": "packs/stm32f411ceu6_golden.json"
        },
        {
          "pack": "packs/stm32g431cbu6_golden.json"
        }
      ]
    }
  ]
}
